name: SampleCodeMirror
description: Sample CodeMirror
dependencies:
  angular: 1.0.0
  bootstrap_for_pub: '>=3.3.0+5 <4.0.0'
  browser: any
  codemirror: any
  dnd: any
dependency_overrides:
  html5lib: 0.12.0
transformers:
- bootstrap_for_pub
